name: CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-run:

    strategy:
      fail-fast: false
    
      matrix:
        include:
          - name: Windows
            os: windows-2019
  
          - name: Ubuntu 22.04
            os: ubuntu-22.04
    
    name: Build and run on ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Visual Studio shell
      if: runner.os == 'Windows'
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64

    - name: Install Ninja
      if: runner.os == 'Linux'
      run: |
        sudo apt-get -y install ninja-build

    - name: Install Qt from giallu/qt-lgpl
      uses: giallu/qt-lgpl@v1
      with:
        qt-version: 6.8.1-3
        os: ${{ matrix.os }}

    - name: Configure CMake
      run: cmake -S . -B build -G Ninja

    - name: Build
      run: cmake --build build

    - name: Run test binary
      shell: bash
      run: |
        build/testapp${{ runner.os == 'Windows' && '.exe' || '' }}
